"""made changes to tables bush tables

Revision ID: a6e8a472e02e
Revises: 
Create Date: 2025-05-04 00:38:31.036125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e8a472e02e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admission_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('student_last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('student_dob', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('student_contact', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('student_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('parent_first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('parent_last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('parent_relationship', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('parent_contact', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('parent_email', sa.String(length=100), nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_type', sa.String(length=20), nullable=False))
        batch_op.drop_column('parent_relationship')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('enrollment_number',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('enrollment_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_relationship', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('relationship_type')

    with op.batch_alter_table('admission_forms', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('parent_email')
        batch_op.drop_column('parent_contact')
        batch_op.drop_column('parent_relationship')
        batch_op.drop_column('parent_last_name')
        batch_op.drop_column('parent_first_name')
        batch_op.drop_column('student_email')
        batch_op.drop_column('student_contact')
        batch_op.drop_column('student_dob')
        batch_op.drop_column('student_last_name')
        batch_op.drop_column('student_first_name')

    # ### end Alembic commands ###
